(function (root, factory) {
  let data = root.LUMI_DATA;
  if (!data && typeof module === 'object' && module.exports) data = require('./data.js');
  const api = factory(data);
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.LUMI = api.createEngine();
})(typeof globalThis !== 'undefined' ? globalThis : this, function (DATA) {
  'use strict';
  if (!DATA) throw new Error('LUMI_DATA is required');
  const byId = arr => Object.fromEntries(arr.map(x => [x.id, x]));
  const TYPE = byId(DATA.types), MATERIAL = byId(DATA.materials), GLAZING = byId(DATA.glazing), COMFORT = byId(DATA.comfort), SYSTEM = byId(DATA.systems);
  const DEFAULT_STATE = Object.freeze({step:0,width:1400,height:1500,type:'ct_double',scheme:'sc_double_fixed_left',sectionOpenings:[],material:'mat_pvc',thermalMode:'mode_warm',glazing:'gl_2ch',comfort:'cf_none',system:'sys_grazio',systemSelectionMode:'auto',extras:['ex_mosquito'],view:'inside'});
  function createEngine(initialState) {
    const state={...DEFAULT_STATE,...(initialState||{}),sectionOpenings:Array.isArray(initialState?.sectionOpenings)?initialState.sectionOpenings.map(x=>({...x})):[],extras:new Set(Array.isArray(initialState?.extras)?initialState.extras:DEFAULT_STATE.extras)};
    const lookup=(arr,id)=>arr.find(x=>x.id===id), currentType=()=>TYPE[state.type], currentScheme=()=> (DATA.schemes[state.type]||[]).find(x=>x.id===state.scheme)||(DATA.schemes[state.type]||[])[0]||null, currentMaterial=()=>MATERIAL[state.material], currentGlazing=()=>GLAZING[state.glazing], currentComfort=()=>COMFORT[state.comfort], currentSystem=()=>SYSTEM[state.system]||null, currentStep=()=>DATA.stepMeta[state.step]||DATA.stepMeta[0];
    const schemesForType=(typeId=state.type)=>DATA.schemes[typeId]||[];
    function cloneSectionsFromScheme(){const s=currentScheme();state.sectionOpenings=(s?.sections||[]).map((x,i)=>({key:`${s.id}:${i}`,label:x.label,role:x.role,ratio:x.ratio||1,opening:x.defaultOpening||'op_fixed'}));}
    function allowedMaterials(){const s=currentScheme();return s?.allowedMaterials?.length?DATA.materials.filter(m=>s.allowedMaterials.includes(m.id)):DATA.materials.slice();}
    function availableThermalModes(){if(state.material==='mat_pvc')return['mode_warm'];const s=currentScheme();if(!s||state.type==='ct_balcony_block'||state.type==='ct_entrance'||s.mechanism==='lift_slide')return['mode_warm'];return['mode_warm','mode_cold'];}
    function supportsColdAndWarm(){const m=availableThermalModes();return state.material==='mat_aluminum'&&m.includes('mode_warm')&&m.includes('mode_cold');}
    function allowedOpeningsForSection(sec){const s=currentScheme();if(!sec||!s)return[];if(sec.role==='portal_fixed')return['op_fixed'];if(sec.role==='portal')return s.mechanism==='psk'?['op_psk']:s.mechanism==='lift_slide'?['op_lift_slide']:['op_fixed'];if(sec.role==='entrance_door')return['op_turn'];if(sec.role==='balcony_door')return['op_turn','op_tilt_turn'];if(sec.role==='transom')return['op_fixed','op_tilt'];return['op_fixed','op_turn','op_tilt_turn','op_tilt'];}
    function allowedGlazing(){return state.material==='mat_aluminum'&&state.thermalMode==='mode_cold'?DATA.glazing.slice():DATA.glazing.filter(x=>x.id!=='gl_single_glass');}
    function allowedComfort(){const limited=(state.material==='mat_aluminum'&&state.thermalMode==='mode_cold')||state.glazing==='gl_single_glass';return limited?DATA.comfort.filter(c=>['cf_none','cf_solar','cf_safe','cf_crystal'].includes(c.id)):DATA.comfort.slice();}
    function compatibleSystems(){const s=currentScheme();if(!s)return[];const roles=new Set(state.sectionOpenings.map(x=>x.role));return DATA.systems.filter(p=>p.material===state.material&&p.thermalModes.includes(state.thermalMode)&&p.constructionTypes.includes(state.type)&&p.mechanisms.includes(s.mechanism)&&[...roles].every(r=>p.roles.includes(r)));}
    function recommendationScore(p){const props=currentComfort()?.properties||[];let score=(p.scores.value||0)+(p.scores.thermal||0)+Math.min(p.scores.value||0,p.scores.thermal||0)*.5;if(props.includes('thermal'))score+=(p.scores.thermal||0)*2.4;if(props.includes('acoustic'))score+=(p.scores.acoustic||0)*2.6;if(state.type==='ct_panoramic'||state.type==='ct_balcony_glazing')score+=(p.scores.panoramic||0)*1.4;return score;}
    function rankedSystems(){return compatibleSystems().map(system=>({system,score:recommendationScore(system)})).sort((a,b)=>b.score-a.score||DATA.systems.indexOf(a.system)-DATA.systems.indexOf(b.system));}
    function recommendedSystemId(list){const r=list?list.map(system=>({system,score:recommendationScore(system)})).sort((a,b)=>b.score-a.score):rankedSystems();return r[0]?.system.id||null;}
    function explainRecommendation(id=state.system){const s=SYSTEM[id];if(!s)return'Нужен инженерный расчёт.';const props=currentComfort()?.properties||[];if(s.id==='sys_s158')return'Выбрана подъёмно-сдвижная конструкция — в текущем ассортименте ей соответствует ALUMARK S158.';if(s.id==='sys_s50')return'Выбрано холодное алюминиевое остекление без требований к теплоизоляции.';if(props.includes('acoustic')&&s.id==='sys_intelio80')return'Для приоритета «тише» INTELIO 80 имеет наиболее сильную акустическую позицию среди доступных REHAU.';if(props.includes('thermal')&&['sys_intelio80','sys_s70'].includes(s.id))return'Выбран приоритет по теплу, поэтому выше ранжируется более тёплая совместимая система.';if((state.type==='ct_panoramic'||state.type==='ct_balcony_glazing')&&s.id==='sys_s70')return'Для панорамного тёплого алюминиевого остекления S70 ранжируется выше как более мощная система.';return`${s.name} даёт наиболее сбалансированное сочетание назначения и характеристик для выбранного сценария.`;}
    function allowedExtras(){const openings=state.sectionOpenings.map(s=>s.opening),active=state.sectionOpenings.some(s=>s.role==='window'&&['op_turn','op_tilt_turn','op_tilt'].includes(s.opening)),turn=state.sectionOpenings.some(s=>s.role==='window'&&['op_turn','op_tilt_turn'].includes(s.opening)),portal=openings.some(o=>['op_psk','op_lift_slide'].includes(o)),windowPart=state.sectionOpenings.some(s=>['window','transom','balcony_door'].includes(s.role));return DATA.extras.filter(x=>x.requires==='standard_active_window'?active&&!portal:x.requires==='window_sill'?windowPart&&state.type!=='ct_entrance'&&!portal:x.requires==='lockable_window'||x.requires==='turn_window'?turn:true);}
    function validationIssues(){const a=[];if(!Number.isFinite(+state.width)||+state.width<=0)a.push({severity:'error',code:'width',message:'Укажите ширину конструкции.'});if(!Number.isFinite(+state.height)||+state.height<=0)a.push({severity:'error',code:'height',message:'Укажите высоту конструкции.'});if(!currentScheme())a.push({severity:'error',code:'scheme',message:'Выберите схему конструкции.'});if(!compatibleSystems().length)a.push({severity:'error',code:'system',message:'Для этой комбинации нет системы в текущем ассортименте.'});a.push({severity:'info',code:'engineering',message:'Размеры, статический расчёт, вес створок и точная формула стеклопакета подтверждаются после замера и инженерной проверки.'});if(state.system==='sys_s158')a.push({severity:'info',code:'s158_weight',message:'Для ALUMARK S158 дополнительно проверяется масса створки; заявленный предел системы — до 400 кг.'});if(['sys_blitz','sys_grazio'].includes(state.system))a.push({severity:'info',code:'approx_fill',message:'Толщина заполнения для выбранной REHAU в прототипе указана как ориентир и должна быть сверена с производственной комплектацией.'});return a;}
    const canProceed=()=>!validationIssues().some(x=>x.severity==='error');
    function reconcileSections(){const s=currentScheme();if(!s){state.sectionOpenings=[];return;}const exp=s.sections||[];if(state.sectionOpenings.length!==exp.length||state.sectionOpenings.some((x,i)=>x.role!==exp[i].role)){cloneSectionsFromScheme();return;}state.sectionOpenings.forEach((sec,i)=>{sec.label=exp[i].label;sec.ratio=exp[i].ratio||1;const allowed=allowedOpeningsForSection(sec);if(!allowed.includes(sec.opening))sec.opening=exp[i].defaultOpening||allowed[0];});}
    function normalizeState(){const ss=schemesForType();if(!ss.some(x=>x.id===state.scheme))state.scheme=ss[0]?.id||null;reconcileSections();const mats=allowedMaterials();if(!mats.some(x=>x.id===state.material))state.material=mats[0]?.id||'mat_pvc';const tm=availableThermalModes();if(!tm.includes(state.thermalMode))state.thermalMode=tm[0]||'mode_warm';const gl=allowedGlazing();if(!gl.some(x=>x.id===state.glazing))state.glazing=gl.find(x=>x.id==='gl_2ch')?.id||gl[0]?.id;const cf=allowedComfort();if(!cf.some(x=>x.id===state.comfort))state.comfort='cf_none';const candidates=compatibleSystems(),ids=new Set(candidates.map(x=>x.id));if(!(state.systemSelectionMode==='manual'&&ids.has(state.system))){state.systemSelectionMode='auto';state.system=recommendedSystemId(candidates);}const ex=new Set(allowedExtras().map(x=>x.id));[...state.extras].forEach(id=>{if(!ex.has(id))state.extras.delete(id)});state.step=Math.max(0,Math.min(DATA.stepMeta.length-1,Number(state.step)||0));state.width=Number(state.width)||DEFAULT_STATE.width;state.height=Number(state.height)||DEFAULT_STATE.height;if(!['inside','outside','scheme'].includes(state.view))state.view='inside';return state;}
    function reset(){Object.assign(state,{...DEFAULT_STATE});state.sectionOpenings=[];state.extras=new Set(DEFAULT_STATE.extras);cloneSectionsFromScheme();return normalizeState();}
    function dispatch(a){if(!a?.type)return state;switch(a.type){case'SET_STEP':state.step=+a.value;break;case'NEXT_STEP':if(state.step<DATA.stepMeta.length-1)state.step++;break;case'PREV_STEP':if(state.step>0)state.step--;break;case'SET_DIMENSION':if(['width','height'].includes(a.field))state[a.field]=+a.value;break;case'SELECT_TYPE':if(TYPE[a.value]){state.type=a.value;state.scheme=schemesForType(a.value)[0]?.id||null;cloneSectionsFromScheme();state.systemSelectionMode='auto';}break;case'SELECT_SCHEME':if(schemesForType().some(x=>x.id===a.value)){state.scheme=a.value;cloneSectionsFromScheme();state.systemSelectionMode='auto';}break;case'SELECT_OPENING':{const sec=state.sectionOpenings[+a.index];if(sec&&allowedOpeningsForSection(sec).includes(a.value))sec.opening=a.value;state.systemSelectionMode='auto';break;}case'SELECT_MATERIAL':if(allowedMaterials().some(x=>x.id===a.value)){state.material=a.value;state.systemSelectionMode='auto';}break;case'SELECT_THERMAL':if(availableThermalModes().includes(a.value)){state.thermalMode=a.value;state.systemSelectionMode='auto';}break;case'SELECT_GLAZING':if(allowedGlazing().some(x=>x.id===a.value)){state.glazing=a.value;state.systemSelectionMode='auto';}break;case'SELECT_COMFORT':if(allowedComfort().some(x=>x.id===a.value)){state.comfort=a.value;state.systemSelectionMode='auto';}break;case'SELECT_SYSTEM':if(compatibleSystems().some(x=>x.id===a.value)){state.system=a.value;state.systemSelectionMode='manual';}break;case'AUTO_SYSTEM':state.systemSelectionMode='auto';state.system=recommendedSystemId();break;case'TOGGLE_EXTRA':if(allowedExtras().some(x=>x.id===a.value))state.extras.has(a.value)?state.extras.delete(a.value):state.extras.add(a.value);break;case'SET_VIEW':state.view=a.value;break;case'RESET':return reset();}return normalizeState();}
    function snapshot(){return{...state,sectionOpenings:state.sectionOpenings.map(x=>({...x})),extras:[...state.extras]};}
    function hydrate(saved){if(!saved||typeof saved!=='object')return state;Object.assign(state,saved);state.sectionOpenings=Array.isArray(saved.sectionOpenings)?saved.sectionOpenings.map(x=>({...x})):[];state.extras=new Set(Array.isArray(saved.extras)?saved.extras:[]);return normalizeState();}
    cloneSectionsFromScheme();normalizeState();
    return{state,DATA,lookup,currentType,currentScheme,currentMaterial,currentGlazing,currentComfort,currentSystem,currentStep,schemesForType,allowedMaterials,availableThermalModes,supportsColdAndWarm,allowedOpeningsForSection,allowedGlazing,allowedComfort,compatibleSystems,rankedSystems,recommendedSystemId,explainRecommendation,allowedExtras,validationIssues,canProceed,normalizeState,reset,dispatch,snapshot,hydrate};
  }
  return {createEngine,DATA};
});
