(function(root,factory){
let D=root.LUMI_DATA,R=root.LUMI_SCENARIO_RULES;
if(typeof module==='object'&&module.exports){D=D||require('./data.js');R=R||require('./scenario-rules.js');}
const A=factory(D,R);if(typeof module==='object'&&module.exports)module.exports=A;root.LUMI=A.createEngine();
})(typeof globalThis!=='undefined'?globalThis:this,function(D,R){
'use strict';if(!D||!R?.length)throw Error('LUMI data/scenario rules required');
const map=a=>Object.fromEntries(a.map(x=>[x.id,x])),uniq=a=>[...new Set(a)],T=map(D.types),M=map(D.materials),G=map(D.glazing),C=map(D.comfort),S=map(D.systems),E=map(D.extras),O=map(D.openingOptions);
const DEF={step:0,width:1400,height:1500,type:'ct_double',scheme:'sc_double_fixed_left',sectionOpenings:[],material:'mat_pvc',thermalMode:'mode_warm',glazing:'gl_2ch',comfort:'cf_none',system:'sys_grazio',systemSelectionMode:'auto',extras:['ex_mosquito'],view:'inside'},ACT=['op_turn','op_tilt_turn','op_tilt'];
const LOCK={sc_double_fixed_left:{0:['op_fixed'],1:ACT},sc_double_fixed_right:{0:ACT,1:['op_fixed']},sc_double_both_active:{0:ACT,1:ACT},sc_double_both_fixed:{0:['op_fixed'],1:['op_fixed']},sc_pan_fixed:{0:['op_fixed']},sc_pan_2:{0:['op_fixed'],1:ACT},sc_pan_3:{0:['op_fixed'],1:ACT,2:['op_fixed']},sc_pan_multi:{0:['op_fixed'],1:ACT,2:['op_fixed'],3:['op_fixed']},sc_pan_psk:{0:['op_psk'],1:['op_fixed']},sc_pan_lift_slide:{0:['op_lift_slide'],1:['op_fixed']},sc_bb_double_window:{0:['op_fixed'],1:ACT,2:['op_turn','op_tilt_turn']},sc_bb_fixed_window:{0:['op_fixed'],1:['op_turn','op_tilt_turn']},sc_bb_active_window:{0:ACT,1:['op_turn','op_tilt_turn']},sc_en_single:{0:['op_turn']},sc_en_side:{0:['op_turn'],1:['op_fixed']},sc_en_double:{0:['op_turn'],1:['op_turn']},sc_en_two_sides:{0:['op_fixed'],1:['op_turn'],2:['op_fixed']},sc_en_transom:{0:['op_turn'],1:['op_fixed']},sc_en_psk:{0:['op_psk'],1:['op_fixed']},sc_en_lift_slide:{0:['op_lift_slide'],1:['op_fixed']}};
const mode=x=>x==='warm'?'mode_warm':x;
function createEngine(init){const st={...DEF,...(init||{}),sectionOpenings:Array.isArray(init?.sectionOpenings)?init.sectionOpenings.map(x=>({...x})):[],extras:new Set(Array.isArray(init?.extras)?init.extras:DEF.extras)};const lookup=(a,id)=>a.find(x=>x.id===id),schemes=(t=st.type)=>D.schemes[t]||[],scheme=()=>schemes().find(x=>x.id===st.scheme)||schemes()[0]||null,currentType=()=>T[st.type],currentMaterial=()=>M[st.material],currentGlazing=()=>G[st.glazing],currentComfort=()=>C[st.comfort],currentSystem=()=>S[st.system]||null,currentStep=()=>D.stepMeta[st.step]||D.stepMeta[0],rulesFor=(t=st.type,sc=st.scheme)=>R.filter(r=>r.construction_type_id===t&&r.scheme_ids.includes(sc)),rule=()=>rulesFor().find(r=>r.material===st.material&&mode(r.thermal_mode)===st.thermalMode)||null;
function clone(){const s=scheme();st.sectionOpenings=(s?.sections||[]).map((x,i)=>({key:`${s.id}:${i}`,label:x.label,role:x.role,ratio:x.ratio||1,opening:x.defaultOpening||'op_fixed'}));}
const allowedMaterials=()=>uniq(rulesFor().map(r=>r.material)).map(id=>M[id]).filter(Boolean),availableThermalModes=()=>uniq(rulesFor().filter(r=>r.material===st.material).map(r=>mode(r.thermal_mode))),supportsColdAndWarm=()=>st.material==='mat_aluminum'&&availableThermalModes().length>1;
function allowedOpeningsForSection(sec){const s=scheme();if(!s||!sec)return[];const i=st.sectionOpenings.indexOf(sec),locked=LOCK[s.id]?.[i];if(locked)return locked.filter(id=>O[id]);const row=rule()?.opening_options||uniq(rulesFor().flatMap(r=>r.opening_options));let a=sec.role==='portal_fixed'?['op_fixed']:sec.role==='portal'?(s.mechanism==='psk'?['op_psk']:s.mechanism==='lift_slide'?['op_lift_slide']:['op_fixed']):sec.role==='entrance_door'?['op_turn']:sec.role==='balcony_door'?['op_turn','op_tilt_turn']:sec.role==='transom'?['op_fixed','op_tilt']:['op_fixed','op_turn','op_tilt_turn','op_tilt'];const f=a.filter(x=>row.includes(x));return f.length?f:a.filter(x=>x==='op_fixed');}
const allowedGlazing=()=> (rule()?.glazing_options||[]).map(id=>G[id]).filter(Boolean),allowedComfort=()=> (rule()?.comfort_options||[]).map(id=>C[id]).filter(Boolean),compatibleSystems=()=> (rule()?.compatible_systems||[]).map(id=>S[id]).filter(Boolean);
function score(p){const pr=currentComfort()?.properties||[];let n=(p.scores?.value||0)+(p.scores?.thermal||0)+Math.min(p.scores?.value||0,p.scores?.thermal||0)*.5;if(pr.includes('thermal'))n+=(p.scores?.thermal||0)*2.4;if(pr.includes('acoustic'))n+=(p.scores?.acoustic||0)*2.6;if(['ct_panoramic','ct_balcony_glazing'].includes(st.type))n+=(p.scores?.panoramic||0)*1.4;return n;}
const rankedSystems=()=>compatibleSystems().map(system=>({system,score:score(system)})).sort((a,b)=>b.score-a.score||D.systems.indexOf(a.system)-D.systems.indexOf(b.system)),recommendedSystemId=(list=compatibleSystems())=>list.map(system=>({system,score:score(system)})).sort((a,b)=>b.score-a.score||D.systems.indexOf(a.system)-D.systems.indexOf(b.system))[0]?.system.id||null;
function explainRecommendation(id=st.system){const p=S[id],r=rule(),pr=currentComfort()?.properties||[];if(!p||!r)return'Нужен инженерный расчёт.';if(id==='sys_s158')return'Подъёмно-сдвижной сценарий в текущем ассортименте соответствует ALUMARK S158.';if(id==='sys_s50')return'Выбрано холодное алюминиевое остекление; по таблице сценариев доступна ALUMARK S50.';if(pr.includes('acoustic')&&id==='sys_intelio80')return'Для приоритета «тише» INTELIO 80 ранжируется выше среди совместимых REHAU.';if(pr.includes('thermal')&&['sys_intelio80','sys_s70'].includes(id))return'Выбран приоритет по теплу, поэтому выше ранжируется более тёплая совместимая система.';return`${p.name} — рекомендуемый вариант среди систем, разрешённых правилом ${r.rule_id}.`;}
function extraOK(id){const ops=st.sectionOpenings.map(x=>x.opening),active=st.sectionOpenings.some(x=>x.role==='window'&&['op_turn','op_tilt_turn','op_tilt'].includes(x.opening)),turn=st.sectionOpenings.some(x=>x.role==='window'&&['op_turn','op_tilt_turn'].includes(x.opening)),portal=ops.some(x=>['op_psk','op_lift_slide'].includes(x)),win=st.sectionOpenings.some(x=>['window','transom','balcony_door'].includes(x.role));if(id==='ex_mosquito')return active&&!portal;if(id==='ex_sill')return win&&st.type!=='ct_entrance'&&!portal;if(['ex_child_lock','ex_limiter'].includes(id))return turn;return true;}
const allowedExtras=()=> (rule()?.extra_options||[]).filter(extraOK).map(id=>E[id]).filter(Boolean);
function reconcile(){const s=scheme();if(!s){st.sectionOpenings=[];return;}const ex=s.sections||[];if(st.sectionOpenings.length!==ex.length||st.sectionOpenings.some((x,i)=>x.role!==ex[i].role))clone();st.sectionOpenings.forEach((x,i)=>{const q=ex[i];x.label=q.label;x.role=q.role;x.ratio=q.ratio||1;x.key=`${s.id}:${i}`;const a=allowedOpeningsForSection(x);if(!a.includes(x.opening))x.opening=a.includes(q.defaultOpening)?q.defaultOpening:(a[0]||'op_fixed');});}
function normalizeState(){const ss=schemes();if(!ss.some(x=>x.id===st.scheme))st.scheme=ss[0]?.id||null;const mm=allowedMaterials();if(!mm.some(x=>x.id===st.material))st.material=mm[0]?.id||'mat_pvc';const tm=availableThermalModes();if(!tm.includes(st.thermalMode))st.thermalMode=tm[0]||'mode_warm';reconcile();const gg=allowedGlazing();if(!gg.some(x=>x.id===st.glazing))st.glazing=gg.find(x=>x.id==='gl_2ch')?.id||gg[0]?.id||null;const cc=allowedComfort();if(!cc.some(x=>x.id===st.comfort))st.comfort=cc.find(x=>x.id==='cf_none')?.id||cc[0]?.id||null;const cs=compatibleSystems(),ids=new Set(cs.map(x=>x.id));if(!(st.systemSelectionMode==='manual'&&ids.has(st.system))){st.systemSelectionMode='auto';st.system=recommendedSystemId(cs);}const ee=new Set(allowedExtras().map(x=>x.id));[...st.extras].forEach(id=>{if(!ee.has(id))st.extras.delete(id);});st.step=Math.max(0,Math.min(D.stepMeta.length-1,Number(st.step)||0));st.width=Number(st.width)||DEF.width;st.height=Number(st.height)||DEF.height;if(!['inside','outside','scheme'].includes(st.view))st.view='inside';return st;}
function validationIssues(){const a=[],r=rule();if(!Number.isFinite(+st.width)||+st.width<=0)a.push({severity:'error',code:'width',message:'Укажите ширину конструкции.'});if(!Number.isFinite(+st.height)||+st.height<=0)a.push({severity:'error',code:'height',message:'Укажите высоту конструкции.'});if(!scheme())a.push({severity:'error',code:'scheme',message:'Выберите схему конструкции.'});if(!r){a.push({severity:'error',code:'scenario',message:'Для выбранной комбинации нет сценария в таблице правил.'});return a;}if(st.sectionOpenings.some(x=>!allowedOpeningsForSection(x).includes(x.opening)))a.push({severity:'error',code:'opening',message:'Недопустимое открывание.'});if(!r.glazing_options.includes(st.glazing))a.push({severity:'error',code:'glazing',message:'Недопустимый стеклопакет.'});if(!r.comfort_options.includes(st.comfort))a.push({severity:'error',code:'comfort',message:'Недопустимый пакет комфорта.'});if(!r.compatible_systems.includes(st.system))a.push({severity:'error',code:'system',message:'Недопустимая профильная система.'});a.push({severity:'info',code:'scenario_rule',message:`Сценарий ${r.rule_id}: ${r.ui_note}`},{severity:'info',code:'engineering',message:r.engineering_validation});if(st.system==='sys_s158')a.push({severity:'info',code:'s158_weight',message:'Для ALUMARK S158 проверяется масса створки; ориентир — до 400 кг.'});return a;}
const canProceed=()=>!validationIssues().some(x=>x.severity==='error');
function reset(){Object.assign(st,{...DEF});st.sectionOpenings=[];st.extras=new Set(DEF.extras);clone();return normalizeState();}
function dispatch(a){if(!a?.type)return st;switch(a.type){case'SET_STEP':st.step=+a.value;break;case'NEXT_STEP':if(st.step<D.stepMeta.length-1)st.step++;break;case'PREV_STEP':if(st.step>0)st.step--;break;case'SET_DIMENSION':if(['width','height'].includes(a.field))st[a.field]=+a.value;break;case'SELECT_TYPE':if(T[a.value]){st.type=a.value;st.scheme=schemes(a.value)[0]?.id||null;clone();st.systemSelectionMode='auto';}break;case'SELECT_SCHEME':if(schemes().some(x=>x.id===a.value)){st.scheme=a.value;clone();st.systemSelectionMode='auto';}break;case'SELECT_OPENING':{const x=st.sectionOpenings[+a.index];if(x&&allowedOpeningsForSection(x).includes(a.value))x.opening=a.value;st.systemSelectionMode='auto';break;}case'SELECT_MATERIAL':if(allowedMaterials().some(x=>x.id===a.value)){st.material=a.value;st.systemSelectionMode='auto';}break;case'SELECT_THERMAL':if(availableThermalModes().includes(a.value)){st.thermalMode=a.value;st.systemSelectionMode='auto';}break;case'SELECT_GLAZING':if(allowedGlazing().some(x=>x.id===a.value)){st.glazing=a.value;st.systemSelectionMode='auto';}break;case'SELECT_COMFORT':if(allowedComfort().some(x=>x.id===a.value)){st.comfort=a.value;st.systemSelectionMode='auto';}break;case'SELECT_SYSTEM':if(compatibleSystems().some(x=>x.id===a.value)){st.system=a.value;st.systemSelectionMode='manual';}break;case'AUTO_SYSTEM':st.systemSelectionMode='auto';st.system=recommendedSystemId();break;case'TOGGLE_EXTRA':if(allowedExtras().some(x=>x.id===a.value))st.extras.has(a.value)?st.extras.delete(a.value):st.extras.add(a.value);break;case'SET_VIEW':st.view=a.value;break;case'RESET':return reset();}return normalizeState();}
const snapshot=()=>({...st,sectionOpenings:st.sectionOpenings.map(x=>({...x})),extras:[...st.extras]});function hydrate(x){if(!x||typeof x!=='object')return st;Object.assign(st,x);st.sectionOpenings=Array.isArray(x.sectionOpenings)?x.sectionOpenings.map(q=>({...q})):[];st.extras=new Set(Array.isArray(x.extras)?x.extras:[]);return normalizeState();}
clone();normalizeState();return{state:st,DATA:D,SCENARIO_RULES:R,lookup,currentType,currentScheme:scheme,currentMaterial,currentGlazing,currentComfort,currentSystem,currentStep,currentScenarioRule:rule,rulesFor,schemesForType:schemes,allowedMaterials,availableThermalModes,supportsColdAndWarm,allowedOpeningsForSection,allowedGlazing,allowedComfort,compatibleSystems,rankedSystems,recommendedSystemId,explainRecommendation,allowedExtras,validationIssues,canProceed,normalizeState,reset,dispatch,snapshot,hydrate};}
return{createEngine,DATA:D,SCENARIO_RULES:R};
});