(function (root, factory) {
  const rules = factory();
  if (typeof module === 'object' && module.exports) module.exports = rules;
  root.LUMI_SCENARIO_RULES = rules;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  const list = value => String(value || '').split('|').filter(Boolean);
  const rule = (rule_id, construction_type_id, scheme_ids, opening_options, material, thermal_mode, glazing_options, comfort_options, compatible_systems, recommended_logic, extra_options, ui_note, engineering_validation) =>
    Object.freeze({
      rule_id,
      construction_type_id,
      scheme_ids: Object.freeze(list(scheme_ids)),
      opening_options: Object.freeze(list(opening_options)),
      material,
      thermal_mode,
      glazing_options: Object.freeze(list(glazing_options)),
      comfort_options: Object.freeze(list(comfort_options)),
      compatible_systems: Object.freeze(list(compatible_systems)),
      recommended_logic,
      extra_options: Object.freeze(list(extra_options)),
      ui_note,
      engineering_validation
    });

  return Object.freeze([
    rule('R01','ct_single','sc_single_1|sc_single_transom','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_pvc','warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_blitz|sys_grazio|sys_intelio80','BLITZ=доступнее; GRAZIO=рекомендуем; INTELIO80=максимальный комфорт','ex_mosquito|ex_sill|ex_drip|ex_slopes|ex_child_lock|ex_limiter|ex_install|ex_delivery','Открывание назначается активной секции.','Проверить Ш×В, вес створки и стеклопакет.'),
    rule('R02','ct_single','sc_single_1|sc_single_transom','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_aluminum','mode_warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_s60|sys_s70','S60=универсальный; S70=для больших/усиленных конструкций','ex_mosquito|ex_sill|ex_drip|ex_slopes|ex_child_lock|ex_limiter|ex_install|ex_delivery','S50 скрыт, т.к. выбрано тёплое остекление.','Проверить Ш×В и вес.'),
    rule('R03','ct_single','sc_single_1|sc_single_transom','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_aluminum','mode_cold','gl_single_glass|gl_1ch|gl_2ch','cf_none|cf_solar|cf_safe|cf_crystal','sys_s50','S50=единственный текущий холодный алюминиевый вариант','ex_mosquito|ex_sill|ex_drip|ex_slopes|ex_child_lock|ex_limiter|ex_install|ex_delivery',"Не акцентировать 'теплее' для холодной системы.",'Проверить заполнение 4–36 мм.'),
    rule('R04','ct_double','sc_double_fixed_left|sc_double_fixed_right|sc_double_both_active|sc_double_both_fixed','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_pvc','warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_blitz|sys_grazio|sys_intelio80','GRAZIO=рекомендуем; BLITZ=доступнее; INTELIO80=для тишины/тепла','ex_mosquito|ex_sill|ex_drip|ex_slopes|ex_child_lock|ex_limiter|ex_install|ex_delivery','Каждой секции можно назначить своё открывание.','Проверить Ш×В каждой створки.'),
    rule('R05','ct_double','sc_double_fixed_left|sc_double_fixed_right|sc_double_both_active|sc_double_both_fixed','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_aluminum','mode_warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_s60|sys_s70','S60=универсальный; S70=крупнее/теплее','ex_mosquito|ex_sill|ex_drip|ex_slopes|ex_child_lock|ex_limiter|ex_install|ex_delivery','Тёплое алюминиевое окно.','Проверить размеры/вес.'),
    rule('R06','ct_double','sc_double_fixed_left|sc_double_fixed_right|sc_double_both_active|sc_double_both_fixed','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_aluminum','mode_cold','gl_single_glass|gl_1ch|gl_2ch','cf_none|cf_solar|cf_safe|cf_crystal','sys_s50','S50=холодное остекление','ex_mosquito|ex_sill|ex_drip|ex_slopes|ex_child_lock|ex_limiter|ex_install|ex_delivery','Для лоджии/неотапливаемой зоны.','Проверить заполнение.'),
    rule('R07','ct_panoramic','sc_pan_fixed|sc_pan_2|sc_pan_3|sc_pan_multi','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_pvc','warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_blitz|sys_grazio|sys_intelio80','INTELIO80/GRAZIO предпочтительнее; BLITZ только при допустимых размерах','ex_mosquito|ex_sill|ex_drip|ex_slopes|ex_child_lock|ex_limiter|ex_install|ex_delivery','Панорамное — формат, а не отдельный материал.','Обязательная проверка статики и габаритов.'),
    rule('R08','ct_panoramic','sc_pan_psk','op_psk','mat_pvc','warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_blitz|sys_grazio|sys_intelio80','GRAZIO/INTELIO80 предпочтительнее для комфорта; BLITZ при допустимой конфигурации','ex_install|ex_delivery|ex_slopes','При выборе PSK автоматически скрыть обычные открывания.','Проверить допустимые размеры портала и фурнитуру PSK.'),
    rule('R09','ct_panoramic','sc_pan_fixed|sc_pan_2|sc_pan_3|sc_pan_multi','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_aluminum','mode_warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_s60|sys_s70','S70 предпочтительно для крупных проёмов; S60 для умеренных размеров','ex_mosquito|ex_sill|ex_drip|ex_slopes|ex_child_lock|ex_limiter|ex_install|ex_delivery','Тёплое панорамное алюминиевое остекление.','Статика и размеры обязательны.'),
    rule('R10','ct_panoramic','sc_pan_lift_slide','op_lift_slide','mat_aluminum','mode_warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_s158','S158=единственная текущая подъёмно-сдвижная система','ex_install|ex_delivery|ex_slopes','Показывать S158 сразу как рекомендованный результат.','Проверить размер, вес створки ≤400 кг и заполнение 10–50 мм.'),
    rule('R11','ct_panoramic','sc_pan_fixed|sc_pan_2|sc_pan_3|sc_pan_multi','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_aluminum','mode_cold','gl_single_glass|gl_1ch|gl_2ch','cf_none|cf_solar|cf_safe|cf_crystal','sys_s50','S50=холодная панорама/витраж','ex_drip|ex_install|ex_delivery','Не предлагать для отапливаемого жилого помещения.','Проверить заполнение 4–36 мм.'),
    rule('R12','ct_balcony_block','sc_bb_window_left|sc_bb_window_right|sc_bb_double_window|sc_bb_fixed_window|sc_bb_active_window','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_pvc','warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_blitz|sys_grazio|sys_intelio80','GRAZIO=рекомендуем; BLITZ=доступнее; INTELIO80=максимум комфорта','ex_mosquito|ex_sill|ex_drip|ex_slopes|ex_child_lock|ex_limiter|ex_install|ex_delivery','Отдельно задавать открывание оконной части; дверь — распашная.','Проверить размеры двери и окна.'),
    rule('R13','ct_balcony_block','sc_bb_window_left|sc_bb_window_right|sc_bb_double_window|sc_bb_fixed_window|sc_bb_active_window','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_aluminum','mode_warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_s60|sys_s70','S60=основной; S70=усиленный','ex_mosquito|ex_sill|ex_drip|ex_slopes|ex_child_lock|ex_limiter|ex_install|ex_delivery','Обычный балконный блок, не подъёмно-сдвижной.','Проверить дверное заполнение и фурнитуру.'),
    rule('R14','ct_balcony_glazing','sc_bg_straight_2|sc_bg_straight_3|sc_bg_straight_4|sc_bg_straight_5plus|sc_bg_l|sc_bg_u','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_aluminum','mode_cold','gl_single_glass|gl_1ch|gl_2ch','cf_none|cf_solar|cf_safe|cf_crystal','sys_s50','S50=холодное остекление лоджии','ex_mosquito|ex_drip|ex_install|ex_delivery','Для неотапливаемого балкона/лоджии.','Проверить общую геометрию и ветровую нагрузку.'),
    rule('R15','ct_balcony_glazing','sc_bg_straight_2|sc_bg_straight_3|sc_bg_straight_4|sc_bg_straight_5plus|sc_bg_l|sc_bg_u','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_aluminum','mode_warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_s60|sys_s70','S60=тёплое; S70=для крупных/усиленных конструкций','ex_mosquito|ex_sill|ex_drip|ex_slopes|ex_install|ex_delivery','Тёплое алюминиевое остекление.','Проверить геометрию/ветровую нагрузку.'),
    rule('R16','ct_balcony_glazing','sc_bg_straight_2|sc_bg_straight_3|sc_bg_straight_4|sc_bg_straight_5plus|sc_bg_l|sc_bg_u','op_fixed|op_turn|op_tilt_turn|op_tilt','mat_pvc','warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_blitz|sys_grazio|sys_intelio80','GRAZIO/INTELIO80 предпочтительнее; BLITZ по расчёту','ex_mosquito|ex_sill|ex_drip|ex_slopes|ex_install|ex_delivery','Тёплая ПВХ-лоджия.','Статика/ветровая нагрузка/размеры обязательны.'),
    rule('R17','ct_entrance','sc_en_single|sc_en_side|sc_en_double|sc_en_two_sides|sc_en_transom','op_turn','mat_aluminum','mode_warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_s60|sys_s70','S60=основной; S70=усиленный/крупный','ex_install|ex_delivery|ex_slopes','Распашная входная группа.','Проверить дверную фурнитуру, порог, размеры и заполнение.'),
    rule('R18','ct_entrance','sc_en_psk','op_psk','mat_pvc','warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_blitz|sys_grazio|sys_intelio80','GRAZIO/INTELIO80 предпочтительнее; BLITZ по расчёту','ex_install|ex_delivery|ex_slopes','Панорамный выход PSK, не основная уличная входная дверь.','Проверить систему PSK и размеры.'),
    rule('R19','ct_entrance','sc_en_lift_slide','op_lift_slide','mat_aluminum','mode_warm','gl_1ch|gl_2ch','cf_none|cf_warm|cf_quiet|cf_solar|cf_yearround|cf_safe|cf_quiet_safe|cf_crystal','sys_s158','S158=единственная текущая подъёмно-сдвижная система','ex_install|ex_delivery|ex_slopes','Террасный/панорамный портал.','Проверить створку до 400 кг, габариты и заполнение 10–50 мм.')
  ]);
});